name: build-debug-apk

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install SDK packages & accept licenses
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        yes | sdkmanager --licenses || true

    - name: Build debug APK
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.7
        arguments: |
          --stacktrace
          --warning-mode all
          --console=plain
          clean
          :app:assembleDebug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: chatwebplus-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
